[package]
name = "commons"
version = "0.1.0"
authors = ["Stefan Junker <mail@stefanjunker.de>"]
edition = "2018"

[dependencies]
actix-web = "^2.0"
env_logger = "^0.6.0"
failure = "^0.1.5"
lazy_static = "^1.2.0"
log = "^0.4.6"
prometheus = { git = "https://github.com/pingcap/rust-prometheus.git", rev = "6a02b0d2943f8fffce672e236e22c6f925184d93"}
serde = "^1.0.70"
serde_json = "^1.0.34"
tokio = "^0.2"
url = "^1.7.2"
futures = "^0.3"

[dev-dependencies]
twoway = "^0.2"
mockito = "^0.20.0"
