[package]
name = "commons"
version = "0.1.0"
authors = ["Stefan Junker <mail@stefanjunker.de>"]
edition = "2018"

[dependencies]
actix-web = "^4.0.0-beta.3"
env_logger = "^0.8"
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "^1.2.0"
log = "^0.4.6"
prometheus = "0.12"
serde = "^1.0.70"
serde_json = "^1.0.34"
serde_derive = "^1.0.123"
tokio = { version = "1.5", features = [ "rt-multi-thread" ] }
url = "^2.2"
futures = "^0.3"
opentelemetry = "0.4.0"
opentelemetry-jaeger = "0.3.0"
reqwest = "^0.11"
thrift = "0.13"
actix-service = "2.0.0-beta.4"

[dev-dependencies]
twoway = "^0.2"
mockito = "^0.30.0"
